// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAM8-noN5W81jnIx4JPu4tixmYVFGLfCTE',
    appId: '1:485185561829:web:1df5e06e028a9e4374a00c',
    messagingSenderId: '485185561829',
    projectId: 'momind-app-90e32',
    authDomain: 'momind-app-90e32.firebaseapp.com',
    storageBucket: 'momind-app-90e32.firebasestorage.app',
    measurementId: 'G-N0FND9534S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrQzTHsPPjzisQoSUxojl-WCQlJQgsmTM',
    appId: '1:485185561829:android:40fe8daba11cb67574a00c',
    messagingSenderId: '485185561829',
    projectId: 'momind-app-90e32',
    storageBucket: 'momind-app-90e32.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhYriyUF1NZa1a9BgbN7QTVCg49bVlMdQ',
    appId: '1:485185561829:ios:0ee94a12bfea07c774a00c',
    messagingSenderId: '485185561829',
    projectId: 'momind-app-90e32',
    storageBucket: 'momind-app-90e32.firebasestorage.app',
    iosBundleId: 'com.example.momindfinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAhYriyUF1NZa1a9BgbN7QTVCg49bVlMdQ',
    appId: '1:485185561829:ios:0ee94a12bfea07c774a00c',
    messagingSenderId: '485185561829',
    projectId: 'momind-app-90e32',
    storageBucket: 'momind-app-90e32.firebasestorage.app',
    iosBundleId: 'com.example.momindfinal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAM8-noN5W81jnIx4JPu4tixmYVFGLfCTE',
    appId: '1:485185561829:web:db7582f803cfb70774a00c',
    messagingSenderId: '485185561829',
    projectId: 'momind-app-90e32',
    authDomain: 'momind-app-90e32.firebaseapp.com',
    storageBucket: 'momind-app-90e32.firebasestorage.app',
    measurementId: 'G-JJ76EK8YNW',
  );
}
